services:
  # url https://localhost:8980/?server=host.docker.internal 
  adminer:
    image: adminer:5
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8980:8080"
    restart: always

  mariadb:
    image: mariadb:10.11
    container_name: mariadb-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: local
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "33062:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: local
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
      POSTGRES_USER: user
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis-db
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
